"use client";

import { FormEvent, useEffect, useState } from "react";
import Header from "@/components/Header";
import { accessToken } from "@/lib/client-auth";

type Report = { id:string;target_type:"list"|"item";reason:string;details:string|null;reporter_email:string|null;status:string;admin_note:string|null;created_at:string;wish_lists?:{subject_name?:string;occasion?:string;share_token?:string}|null;wish_items?:{title?:string;url?:string|null;retailer?:string|null}|null };
type AdminUser = { id:string;email:string;firstName:string;createdAt:string;confirmedAt:string|null;lastSignInAt:string|null;claimCount:number;wishCount:number;lists:Array<{id:string;subject_name:string;occasion:string;share_token:string;created_at:string;moderation_status:string;itemCount:number}> };
type UserResponse = { users:AdminUser[];pagination:{page:number;perPage:number;total:number;lastPage:number};summary:{totalUsers:number;totalLists:number;totalWishes:number;totalClaims:number} };

function date(value:string|null){return value?new Date(value).toLocaleString():"Never";}

export default function AdminPage(){
  const [tab,setTab]=useState<"users"|"reports">("users");
  const [reports,setReports]=useState<Report[]>([]);
  const [directory,setDirectory]=useState<UserResponse|null>(null);
  const [search,setSearch]=useState("");
  const [activeSearch,setActiveSearch]=useState("");
  const [error,setError]=useState("");
  const [maintenance,setMaintenance]=useState("");
  const [loading,setLoading]=useState(true);
  const [notes,setNotes]=useState<Record<string,string>>({});

  async function adminToken(){const token=await accessToken();if(!token)throw new Error("Sign in with the admin account first.");return token;}
  async function loadUsers(page=1,query=activeSearch){setLoading(true);setError("");try{const token=await adminToken();const params=new URLSearchParams({page:String(page)});if(query)params.set("search",query);const res=await fetch(`/api/admin/users?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not load users");setDirectory(data);}catch(e){setError(e instanceof Error?e.message:"Could not load users");}finally{setLoading(false);}}
  async function loadReports(){setLoading(true);setError("");try{const token=await adminToken();const res=await fetch("/api/admin/reports",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not load reports");setReports(data.reports||[]);}catch(e){setError(e instanceof Error?e.message:"Could not load reports");}finally{setLoading(false);}}
  useEffect(()=>{loadUsers(1,"");},[]);
  function switchTab(next:"users"|"reports"){setTab(next);setError("");setMaintenance("");if(next==="users")loadUsers();else loadReports();}
  function submitSearch(e:FormEvent){e.preventDefault();const query=search.trim();setActiveSearch(query);loadUsers(1,query);}
  async function deleteUser(user:AdminUser){const typed=prompt(`This permanently deletes ${user.email}, every owned list, every wish, and attached gift claims.\n\nType the full email address to confirm:`);if(typed===null)return;if(typed.trim().toLowerCase()!==user.email.toLowerCase()){setError("Account deletion cancelled because the email did not match.");return;}const token=await adminToken();const res=await fetch(`/api/admin/users/${user.id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({confirmationEmail:typed})});const data=await res.json();if(!res.ok){setError(data.error||"Could not delete account");return;}setMaintenance(`${user.email} and all owned data were deleted.`);await loadUsers(directory?.pagination.page||1);}
  async function act(id:string,action:string){const token=await adminToken();const res=await fetch(`/api/admin/reports/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({action,note:notes[id]||""})});const data=await res.json();if(!res.ok){setError(data.error||"Moderation action failed");return;}await loadReports();}
  async function cacheLegacyImages(){setError("");setMaintenance("Caching up to five legacy images…");try{const token=await adminToken();const res=await fetch("/api/admin/images/backfill",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const data=await res.json();if(!res.ok)throw new Error(data.error||"Image maintenance failed");setMaintenance(`${data.cached} images cached, ${data.failed} failed, ${data.remaining} remaining.`);}catch(e){setError(e instanceof Error?e.message:"Image maintenance failed");setMaintenance("");}}

  return <main><Header/><section className="admin-shell">
    <div className="admin-top"><div><div className="eyebrow">WISH NORTH ADMIN</div><h1>{tab==="users"?"Users & lists":"Abuse & takedowns"}</h1><p>{tab==="users"?"Monitor accounts, activity, wish lists, and account status.":"Review reports, hide content, restore it, dismiss reports, or permanently delete content."}</p></div><div className="admin-actions">{tab==="reports"?<button className="button button-ghost" onClick={cacheLegacyImages}>Cache legacy images</button>:null}<button className="button button-ghost" onClick={()=>tab==="users"?loadUsers(directory?.pagination.page||1):loadReports()}>Refresh</button></div></div>
    <div className="admin-tabs"><button className={tab==="users"?"active":""} onClick={()=>switchTab("users")}>Users & lists</button><button className={tab==="reports"?"active":""} onClick={()=>switchTab("reports")}>Abuse & takedowns</button></div>
    {maintenance?<div className="success-box">{maintenance}</div>:null}{error?<div className="error-box">{error}</div>:null}
    {tab==="users"?<>
      {directory?<div className="admin-summary"><div><strong>{directory.summary.totalUsers}</strong><span>Users</span></div><div><strong>{directory.summary.totalLists}</strong><span>Account lists</span></div><div><strong>{directory.summary.totalWishes}</strong><span>Wishes</span></div><div><strong>{directory.summary.totalClaims}</strong><span>Gift claims</span></div></div>:null}
      <form className="admin-search" onSubmit={submitSearch}><input type="search" placeholder="Search by name or email" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button button-dark">Search</button>{activeSearch?<button type="button" className="button button-ghost" onClick={()=>{setSearch("");setActiveSearch("");loadUsers(1,"");}}>Clear</button>:null}</form>
      {loading?<div className="loading">Loading users…</div>:directory?.users.length?<div className="admin-user-list">{directory.users.map(user=><article className="admin-user-card" key={user.id}><div className="admin-user-main"><div className="admin-avatar">{(user.firstName||user.email||"?").slice(0,1).toUpperCase()}</div><div><h3>{user.firstName||"Unnamed user"}</h3><a href={`mailto:${user.email}`}>{user.email}</a><div className="admin-meta"><span>Joined {date(user.createdAt)}</span><span>Last sign-in {date(user.lastSignInAt)}</span></div></div><span className={`status-pill ${user.confirmedAt?"confirmed":"pending"}`}>{user.confirmedAt?"Confirmed":"Pending"}</span></div><div className="admin-user-counts"><span><b>{user.lists.length}</b> lists</span><span><b>{user.wishCount}</b> wishes</span><span><b>{user.claimCount}</b> claims</span></div>{user.lists.length?<details className="admin-list-details"><summary>View owned lists</summary><div>{user.lists.map(list=><div className="admin-owned-list" key={list.id}><div><strong>{list.subject_name}’s {list.occasion} list</strong><span>{list.itemCount} {list.itemCount===1?"wish":"wishes"} · {list.moderation_status}</span></div><a href={`/share/${list.share_token}`} target="_blank" rel="noreferrer">Open list ↗</a></div>)}</div></details>:<p className="admin-no-lists">No lists attached to this account.</p>}<div className="admin-user-danger"><button className="plain-link danger-link" onClick={()=>deleteUser(user)}>Delete account and all data</button></div></article>)}</div>:<div className="mini-empty">No users found.</div>}
      {directory&&directory.pagination.lastPage>1?<div className="admin-pagination"><button className="button button-ghost" disabled={directory.pagination.page<=1} onClick={()=>loadUsers(directory.pagination.page-1)}>Previous</button><span>Page {directory.pagination.page} of {directory.pagination.lastPage} · {directory.pagination.total} users</span><button className="button button-ghost" disabled={directory.pagination.page>=directory.pagination.lastPage} onClick={()=>loadUsers(directory.pagination.page+1)}>Next</button></div>:null}
    </>:<>{loading?<div className="loading">Loading reports…</div>:<div className="admin-grid">{reports.length?reports.map(r=><article className="admin-card" key={r.id}><div className="admin-card-head"><div><span className="status-pill">{r.status}</span><h3>{r.target_type==="item"?(r.wish_items?.title||"Reported item"):`${r.wish_lists?.subject_name||"Reported"} list`}</h3><div className="admin-meta"><span>{r.reason}</span><span>{date(r.created_at)}</span>{r.reporter_email?<span>{r.reporter_email}</span>:null}</div></div></div>{r.details?<p>{r.details}</p>:null}{r.wish_items?.url?<p><a className="text-link" href={r.wish_items.url} target="_blank" rel="noreferrer">Open retailer item ↗</a></p>:null}{r.wish_lists?.share_token?<p><a className="text-link" href={`/share/${r.wish_lists.share_token}`} target="_blank" rel="noreferrer">Open shared list ↗</a></p>:null}<textarea className="admin-note" placeholder="Internal moderation note" value={notes[r.id]||""} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))}/><div className="admin-actions"><button className="button button-dark" onClick={()=>act(r.id,"hide")}>Hide content</button><button className="button button-ghost" onClick={()=>act(r.id,"restore")}>Restore</button><button className="button button-ghost" onClick={()=>act(r.id,"dismiss")}>Dismiss report</button><button className="plain-link danger-link" onClick={()=>confirm("Permanently delete this content? This cannot be undone.")&&act(r.id,"delete")}>Delete permanently</button></div></article>):<div className="mini-empty">No abuse reports yet.</div>}</div>}</>}
  </section></main>;
}
