import { NextResponse } from "next/server";
import * as cheerio from "cheerio";
import { assertPublicHttpUrl } from "@/lib/urlSafety";
import { cacheProductImage } from "@/lib/imageCache";
import { fetchPublicUrl, readTextLimited } from "@/lib/remoteFetch";
import { enforceRateLimit, rejectBot } from "@/lib/rateLimit";
import { normalizeProductUrl, normalizeRetailer, retailerDomain, normalizeTitle, productKey } from "@/lib/normalize";
function cleanPrice(input: unknown) { if (typeof input === "number") return input.toFixed(2); if (typeof input !== "string") return ""; const m=input.replace(/,/g,"").match(/(?:\$|USD\s*)?([0-9]+(?:\.[0-9]{1,2})?)/i); return m?m[1]:""; }
export async function POST(req:Request){try{await enforceRateLimit(req,"import-url",20,600);const body=await req.json();rejectBot(body);const parsed=await assertPublicHttpUrl(String(body.url));const{response,finalUrl}=await fetchPublicUrl(parsed,{timeoutMs:8_000,maxRedirects:5,headers:{"user-agent":"Mozilla/5.0 (compatible; WishNorth/1.0; +https://wishnorth.netlify.app)",accept:"text/html,application/xhtml+xml"}});if(!response.ok)throw new Error(`Retailer returned ${response.status}`);const contentType=response.headers.get("content-type")||"";if(!contentType.includes("text/html")&&!contentType.includes("application/xhtml+xml"))throw new Error("URL is not a product web page");const html=await readTextLimited(response,3_000_000);const $=cheerio.load(html);let title=$('meta[property="og:title"]').attr("content")||$('meta[name="twitter:title"]').attr("content")||$("title").text()||"";let imageUrl=$('meta[property="og:image"]').attr("content")||$('meta[name="twitter:image"]').attr("content")||"";let price=$('meta[property="product:price:amount"]').attr("content")||$('meta[itemprop="price"]').attr("content")||"";let retailer=$('meta[property="og:site_name"]').attr("content")||"";$('script[type="application/ld+json"]').each((_,el)=>{try{const json=JSON.parse($(el).text());const nodes=Array.isArray(json)?json:json['@graph']?json['@graph']:[json];for(const node of nodes){if(!node||typeof node!=="object")continue;if(node['@type']==="Product"||(Array.isArray(node['@type'])&&node['@type'].includes("Product"))){title=node.name||title;const img=Array.isArray(node.image)?node.image[0]:typeof node.image==="object"?node.image?.url:node.image;imageUrl=img||imageUrl;const offers=Array.isArray(node.offers)?node.offers[0]:node.offers;price=offers?.price||offers?.lowPrice||price;if(node.brand&&!retailer)retailer=typeof node.brand==="string"?node.brand:node.brand.name||retailer;}}}catch{}});if(imageUrl){try{imageUrl=new URL(imageUrl,finalUrl).toString()}catch{imageUrl=""}}const cached=await cacheProductImage(imageUrl);const canonical=normalizeProductUrl(finalUrl.toString());const cleanTitle=title.trim().replace(/\s+/g," ").slice(0,300);const store=normalizeRetailer(retailer,canonical);return NextResponse.json({title:cleanTitle,imageUrl:cached.imageUrl,imageSourceUrl:cached.sourceUrl,price:cleanPrice(price),retailer:store,retailerDomain:retailerDomain(canonical),finalUrl:canonical,normalizedTitle:normalizeTitle(cleanTitle),productKey:productKey(cleanTitle,canonical)});}catch(e){const status=(e as Error&{status?:number}).status||422;return NextResponse.json({error:status===429?"Too many product imports. Please try again in a few minutes.":status===503?"Product import is temporarily unavailable. Please enter the details manually.":"That store would not let Wish North read the product automatically. You can still enter the item details manually."},{status});}}
