alter table public.wish_lists
  add column if not exists moderation_status text not null default 'active',
  add column if not exists moderation_reason text,
  add column if not exists moderated_at timestamptz;

alter table public.wish_items
  add column if not exists image_source_url text,
  add column if not exists image_cached_at timestamptz,
  add column if not exists normalized_url text,
  add column if not exists normalized_title text,
  add column if not exists retailer_domain text,
  add column if not exists product_key text,
  add column if not exists moderation_status text not null default 'active',
  add column if not exists moderation_reason text,
  add column if not exists moderated_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.trend_events
  add column if not exists product_key text,
  add column if not exists retailer_domain text;

create table if not exists public.abuse_reports (
  id uuid primary key default gen_random_uuid(),
  share_token text not null,
  list_id uuid not null references public.wish_lists(id) on delete cascade,
  item_id uuid references public.wish_items(id) on delete cascade,
  target_type text not null check (target_type in ('list','item')),
  reason text not null,
  details text,
  reporter_email text,
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  admin_note text,
  created_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by uuid references auth.users(id) on delete set null
);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  report_id uuid references public.abuse_reports(id) on delete set null,
  target_type text not null check (target_type in ('list','item')),
  target_id uuid not null,
  action text not null check (action in ('hide','restore','delete','resolve','dismiss')),
  admin_user_id uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.account_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  accepted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists abuse_reports_status_created_idx on public.abuse_reports(status, created_at desc);
create index if not exists abuse_reports_list_idx on public.abuse_reports(list_id);
create index if not exists abuse_reports_item_idx on public.abuse_reports(item_id);
create index if not exists wish_items_product_key_idx on public.wish_items(product_key);
create index if not exists wish_items_normalized_url_idx on public.wish_items(normalized_url);
create index if not exists trend_events_product_key_idx on public.trend_events(product_key);

alter table public.abuse_reports enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.account_consents enable row level security;
revoke all on table public.wish_lists, public.wish_items, public.gift_claims, public.trend_events, public.abuse_reports, public.moderation_actions, public.account_consents from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif']::text[])
on conflict (id) do update set public=excluded.public, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;
